spring.main.allow-bean-definition-overriding=true
spring.jackson.serialization.INDENT_OUTPUT= true

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
#@RestController
spring.data.web.pageable.max-page-size=50
#@RepositoryRestResource
spring.data.rest.max-page-size=50

# SERVER
#server.servlet.context-path=/nails-api
server.port = 7878

#EXCEPTION HANDLER
server.error.whitelabel.enabled=false
spring.mvc.throw-exception-if-no-handler-found=true
spring.resources.add-mappings=false

#LOG
logging.pattern.file= "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
logging.level.root=WARN
logging.level.{PACKAGE_NAME}=DEBUG
logging.level.org.springframework.web=WARN
logging.file.path=/var/log/{APP_ID}
logging.file.name=/var/log/{APP_ID}/log.log
logging.file=${catalina.home}/logs/spam.log

management.endpoints.web.exposure.include=* 
security.basic.enabled=false
spring.jpa.open-in-view=false

#enable liquibase
spring.liquibase.enabled=true

#Email
spring.mail.default-encoding=UTF-8
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=cakeshophcmute@gmail.com
spring.mail.password=gfvffheaymxxvnso
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#Thread pool
thread.pool.size=10
thread.pool.queue.size=100

# Feign client
feign.client.config.default.connectTimeout=60000
feign.client.config.default.readTimeout=60000

# Maximum tenants cached and expire time after access
multitenancy.datasource-cache.maximumSize=300
multitenancy.datasource-cache.expireAfterAccess=10

# Master tenant config // su dung cho tenant dac biet nhat dùng cho ca he thong
multitenancy.master.datasource.url=jdbc:mysql://localhost:3306/db_master?useUnicode=yes&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
multitenancy.master.datasource.username=admin
multitenancy.master.datasource.password=admin
multitenancy.master.datasource.driverClassName=com.mysql.cj.jdbc.Driver
multitenancy.master.datasource.connectionTimeout=20000
multitenancy.master.datasource.maxPoolSize=10
multitenancy.master.datasource.idleTimeout=10000
multitenancy.master.datasource.minIdle=5
multitenancy.master.datasource.poolName=masterdb-pool
multitenancy.master.datasource.showSql=true
multitenancy.master.datasource.ddlAuto=none


# Tenant config // su dung cho tung tenant riêng biet
multitenancy.tenant.datasource.url=jdbc:mysql://localhost:3306/db_tenant?useUnicode=yes&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
multitenancy.tenant.datasource.username=admin
multitenancy.tenant.datasource.password=admin
multitenancy.tenant.datasource.driverClassName=com.mysql.cj.jdbc.Driver
multitenancy.tenant.datasource.connectionTimeout=20000
multitenancy.tenant.datasource.maxPoolSize=10
multitenancy.tenant.datasource.idleTimeout=10000
multitenancy.tenant.datasource.minIdle=5
multitenancy.tenant.datasource.showSql=true
multitenancy.tenant.datasource.ddlAuto=none
multitenancy.tenant.liquibase.enabled=true
multitenancy.tenant.liquibase.change-log=classpath:liquibase/db.changelog-master.xml
# MyISam
#multitenancy.tenant.datasource.dialect=org.hibernate.dialect.MySQL5Dialect
# InnoDb
multitenancy.tenant.datasource.dialect=org.hibernate.dialect.MySQL5InnoDBDialect

#oauth2 key
auth.signing.key=T7PfKrPGvK

#Auth service
auth.internal.base.url=http://localhost:8787

#Media service
media.internal.base.url=http://localhost:7474

#Internal authorization
auth.internal.basic.username=abc_client
auth.internal.basic.password=abc123
auth.internal.username=internal
auth.internal.password=admin123654
auth.internal.employee.username=employeeinternal
auth.internal.employee.password=admin123654
auth.internal.user.username=userinternal
auth.internal.user.password=admin123654

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin@2o23.hcm

rabbitmq.convert.video.queue=CONVERT_VIDEO_QUEUE
rabbitmq.update.video.queue=UPDATE_VIDEO_QUEUE
rabbitmq.media.queue=MOVIE_QUEUE_MEDIA
rabbitmq.app=MOVIE

# Google config
social.google.web.client-id=144532728035-6lvddrcid9a6r45eas7mud03mqu2lgrr.apps.googleusercontent.com
social.google.web.client-secret=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
social.google.web.redirect-uri=http://localhost:3636/auth/google/callback
social.google.ios.client-id=144532728035-ug7o416fghvq4dapfuf1qrmppepsqvss.apps.googleusercontent.com
social.google.android.client-id=144532728035-rbu66k0hirdckcp1ato2kff2m83uta4g.apps.googleusercontent.com

social.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo
social.google.token-uri=https://oauth2.googleapis.com/token

# SNS config
sns.internal.base.url=http://localhost:8686
sns.application.id=8947096369924096
